name: Build
on: workflow_dispatch
jobs:
  build-the-thing:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:latest
      options: --cpus 1
    steps:
      - name: install_git
        run: apt install git-all -y
      - name: download_codeclient
        run: git clone https://github.com/DFOnline/CodeClient.git && ls && pwd
